;;; Skyline-Tool src/gui/gui-character-appearance.lisp
;;; Appearance tab for Character Inspector

(in-package :skyline-tool)

;; Appearance tab - read-only display
(defmethod display-appearance-tab (frame pane)
  (let ((resource (frame-resource frame)))
    (clim:formatting-table (pane)
      (clim:formatting-row (pane)
        (clim:formatting-cell (pane :align-x :right) (format pane "Hair Color: "))
        (clim:formatting-cell (pane :align-x :left)
          (destructuring-bind (name r g b)
            (elt *common-palette* (game-resource-character-hair-color resource))
            (print-wide-pixel (rgb->palette r g b) pane)
            (format pane "  ~a" (title-case (string name)))))))
      (clim:formatting-row (pane)
        (clim:formatting-cell (pane :align-x :right) (format pane "Skin Color: "))
        (clim:formatting-cell (pane :align-x :left)
          (destructuring-bind (name r g b)
            (elt *common-palette* (game-resource-character-skin-color resource))
            (print-wide-pixel (rgb->palette r g b) pane)
            (format pane "  ~a" (title-case (string name)))))))
      (clim:formatting-row (pane)
        (clim:formatting-cell (pane :align-x :right) (format pane "Clothes Color: "))
        (clim:formatting-cell (pane :align-x :left)
          (destructuring-bind (name r g b)
            (elt *common-palette* (game-resource-character-clothes-color resource))
            (print-wide-pixel (rgb->palette r g b) pane)
            (format pane "  ~a" (title-case (string name)))))))
      (clim:formatting-row (pane)
        (clim:formatting-cell (pane :align-x :right) (format pane "Head: "))
        (clim:formatting-cell (pane :align-x :left) (format pane "~a" (game-resource-character-head resource)))))
      (clim:formatting-row (pane)
        (clim:formatting-cell (pane :align-x :right) (format pane "Body: "))
        (clim:formatting-cell (pane :align-x :left) (format pane "~a" (game-resource-character-body resource)))))))