(clim:define-presentation-method present-pane ((sheet clim:standard-sheet *sh* :class clim:tab-layout-header))
     ((pane clim:tab-panel *sh* :window *root-window*)
          :presentor :gadget-tab)
  (present (back window)
    (with-pushpin (window center *) (tab) (padding 1 2 1 2)
      (clim:tab-frame tab (shadowed-frame-clim (aborder tab-border :show-border t :top :left) :disband! false) (tab) (glyph) (text))))
     ((back window)
     (present back tab-resource)
      (tab-frame tab (shadowed-frame-clim (aborder tab-border :show-border t :top :left) :disband! false) (tab) (glyph) (text)))))