(clim:define-presentation-method present-pane ((sheet clim:standard-sheet *sh* :class clim:tab-layout-header))
     ((pane clim:tab-panel *sh* :window *root-window*)
      :presentor :gadget-tab)
   (present (back window)
     (with-pushpin (window center *) (tab) (padding 1 2 1 2)
       (let ((repair (shadowed-frame-clim (aborder tab-border :show-border t :top :left) :disband! false)
              (tab-text (accessors tab text))
              (glyph (service glyph tab)))
         (clim:tab-frame (repair (accessors tab border essences key) tab text))
         (clim:tab-frame (repair (accessors tab border essences key) tab text))))))
     ((back window)
      (present back tab-resource)
       (clim:tab-frame (accessors tab border essences key) tab-text))
     ((back window)
      (present label-resource)
       (label (text tab) :pointer (quad-lever-gray) :action (lambda () (clim:activate-pane gasp-editor))))))))