(load "setup.lisp")
(ql:quickload :skyline-tool)
(format t "compile-art-5200 exists: ~A~%" (fboundp 'skyline-tool:compile-art-5200))
(format t "compile-music exists: ~A~%" (fboundp 'skyline-tool:compile-music))
(format t "compile-5200-mode-e-bitmap exists: ~A~%" (fboundp 'compile-5200-mode-e-bitmap))
(format t "compile-sound exists: ~A~%" (fboundp 'skyline-tool:compile-sound))
(format t "compile-tileset exists: ~A~%" (fboundp 'compile-tileset))
(format t "compile-font-8×8 exists: ~A~%" (fboundp 'compile-font-8×8))
(format t "dispatch-png% exists: ~A~%" (fboundp 'dispatch-png%))
