(in-package :skyline-tool)

(define-constant +chaos-repeat-patterns+
    #(#()
      #(1 1 1 1 1 1 1 1)
      #(1 2 1 2 1 2 1 2)
      #(1 2 3 2 1 2 3 2)
      #(1 2 3 4 1 2 3 4)
      #(1 2 3 4 5 2 3 4)
      #(1 2 3 4 5 6 3 4)
      #(1 2 3 4 5 6 7 4)
      #(1 2 3 4 5 6 7 8))
  :test 'equalp)

(defun chaos-frame->key (frame-vector)
  (with-output-to-string (stream)
    (loop for byte across frame-vector
          do (format stream "~2,'0X" byte))))

(defun chaos-byte->binary-string (byte)
  (concatenate 'string "%" (format nil "~8,'0B" byte)))

(defun chaos-extract-frame (palette frame-index pose-index)
  (let ((frame (make-array 16 :element-type '(unsigned-byte 8)))
        (nonzero nil))
    (loop for row from 0 below 16
          for destination = (- 15 row)
          for global-y = (+ (* pose-index 16) row)
          do (let ((byte 0))
               (loop for column from 0 below 8
                     for global-x = (+ (* frame-index 8) column)
                     for palette-value = (and (< global-x (array-dimension palette 0))
                                              (< global-y (array-dimension palette 1))
                                              (aref palette global-x global-y))
                     do (when (and palette-value (plusp palette-value))
                          (setf nonzero t)
                          (setf byte (logior byte (ash 1 (- 7 column))))))
               (setf (aref frame destination) byte)))
    (values frame nonzero)))

(defun ensure-chaos-frame-index (frame-vector frame-cache frames)
  (let* ((key (chaos-frame->key frame-vector))
         (existing (gethash key frame-cache)))
    (if existing
        existing
        (let ((index (vector-push-extend (copy-seq frame-vector) frames)))
          (setf (gethash key frame-cache) index)
          index))))

(defun chaos-previous-value (row position)
  (loop for idx downfrom (1- position) downto 0
        for value = (aref row idx)
        when value do (return value)))

(defun fill-chaos-row-indices (row)
  (let* ((length (length row))
         (leading-count (loop for idx from 0 below length
                              while (aref row idx)
                              count 1)))
    (dotimes (position length)
      (when (null (aref row position))
        (let* ((pattern (and (plusp leading-count)
                             (< leading-count (length +chaos-repeat-patterns+))
                             (aref +chaos-repeat-patterns+ leading-count)))
               (value (cond
                        ((and pattern (< position (length pattern)))
                         (let* ((reference (1- (aref pattern position)))
                                (lookup (and (<= 0 reference)
                                             (< reference length)
                                             (aref row reference))))
                           (or lookup (chaos-previous-value row position))))
                        (t (chaos-previous-value row position)))))
          (unless value
            (error "Unable to infer ChaosFight frame index for column ~d" position))
          (setf (aref row position) value))))
    row))

(defun playfield-row->string (palette width y)
  (let ((chars (make-string width)))
    (dotimes (x width)
      (let ((value (and (< x (array-dimension palette 0))
                        (< y (array-dimension palette 1))
                        (aref palette x y))))
        (setf (aref chars x)
              (if (and value (not (zerop value)))
                  #\X
                  #\.))))
    chars))

(defun dominant-playfield-color (palette width y)
  (let ((counts (make-hash-table :test 'eql))
        (best-color 0)
        (best-count 0))
    (dotimes (x width)
      (let ((value (and (< x (array-dimension palette 0))
                        (< y (array-dimension palette 1))
                        (aref palette x y))))
        (when (and value (not (zerop value)))
          (let* ((count (incf (gethash value counts 0))))
            (when (> count best-count)
              (setf best-count count
                    best-color value))))))
    (if (plusp best-count) best-color 0)))

(defun format-playfield-color (color)
  (format nil "$~2,'0X" color))

(defun playfield-color-byte (color region)
  (let ((byte (logand color #xff)))
    (ecase region
      (:secam (let* ((index (mod byte 8))
                     (nybble (* 2 index)))
                (logior (ash nybble 4) nybble)))
      (:ntsc byte)
      (:pal byte))))

(defun compile-2600-font-8x16 (output-bas png-path)
  (let* ((input-path (uiop:ensure-pathname png-path))
         (png (png-read:read-png-file input-path))
         (width (png-read:width png))
         (height (png-read:height png)))
    (unless (and (> width 0) (zerop (mod width 8)))
      (error "Fonts must be a positive multiple of 8 pixels wide; got ~a" width))
    (unless (and (> height 0) (zerop (mod height 16)))
      (error "Fonts must be a positive multiple of 16 pixels tall; got ~a" height))
    (let* ((*machine* 2600)
           (*region* :ntsc)
           (palette (png->palette (png-read:image-data png)
                                  (png-read:transparency png)))
           (chars-per-row (/ width 8))
           (char-rows (/ height 16))
           (char-count (* chars-per-row char-rows))
           (output-path (uiop:ensure-pathname output-bas))
           (base-name (pathname-base-name input-path))
           (label-root (cl-change-case:pascal-case base-name))
           (font-label (format nil "SetFont~a" label-root))
           (data-label "FontData"))
      (ensure-directories-exist output-path)
      (with-open-file (stream output-path
                              :direction :output
                              :if-exists :supersede
                              :if-does-not-exist :create)
        (format stream "~a" font-label)
        (format stream "~%~10tdata ~a" data-label)
        (loop for char from 0 below char-count
              for char-x = (mod char chars-per-row)
              for char-y = (floor char chars-per-row)
              do (loop for row from 15 downto 0
                       for y = (+ (* char-y 16) row)
                       do (let ((value 0))
                            (dotimes (col 8)
                              (let* ((x (+ (* char-x 8) col))
                                     (pixel (and (< x (array-dimension palette 0))
                                                 (< y (array-dimension palette 1))
                                                 (aref palette x y))))
                                (when (and pixel (not (zerop pixel)))
                                  (setf value (logior value (ash 1 (- 7 col)))))))
                            (format stream "~%~12t.byte %~8,'0B" value))))
        (format stream "~%end")
        (format stream "~%~%"))
      output-bas)))

(defun write-chaos-character-output (stream character-name frames frame-map output-path source-path)
  (let* ((target-path (uiop:ensure-pathname output-path))
         (source-pathname (uiop:ensure-pathname source-path))
         (file-name (enough-namestring target-path))
         (source-name (enough-namestring source-pathname))
         (label (format nil "~@[~a~]" character-name))
         (frame-label (format nil "~aFrames" label))
         (map-label (format nil "~aFrameMap" label)))
    (format stream "~10trem Chaos character output")
    (format stream "~%~10trem File: ~a" file-name)
    (format stream "~%~10trem Source: ~a" source-name)
    (format stream "~%~10trem DO NOT EDIT. Generated by compile-chaos-character.")
    (format stream "~%~10tasm")
    (format stream "~%~a:" frame-label)
    (let ((frame-count (length frames)))
      (dotimes (frame-index frame-count)
        (let ((frame-vector (aref frames frame-index)))
          (dotimes (row 16)
            (format stream "~%~12tBYTE ~a"
                    (chaos-byte->binary-string (aref frame-vector row)))))
        (when (< (1+ frame-index) frame-count)
          (format stream "~%"))))
    (format stream "~%end")
    (format stream "~%~10tasm")
    (format stream "~%~a:" map-label)
    (dotimes (pose 16)
      (let ((pose-values (aref frame-map pose)))
        (format stream "~%~12tBYTE ~{~d~^, ~}" (coerce pose-values 'list))))
    (format stream "~%end")
    (format stream "~%~%")))

(defun compile-2600-playfield (output-bas png-path &optional tv-standard)
  (declare (ignore tv-standard))
  (let* ((input-path (uiop:ensure-pathname png-path))
         (png (png-read:read-png-file input-path))
         (width (png-read:width png))
         (height (png-read:height png))
         (rgb (png-read:image-data png))
         (alpha (png-read:transparency png)))
    (unless (member width '(16 32))
      (error "Playfields must be 16 or 32 pixels wide; got ~a" width))
    (unless (<= 6 height 32)
      (error "Playfields must be between 6 and 32 rows; got ~a" height))
    (let* ((target-path (uiop:ensure-pathname output-bas))
           (name (pathname-name target-path))
           (segments (uiop:split-string name :separator "."))
           (maybe-region (when segments (string-upcase (car (last segments)))))
           (base-segments (if has-explicit-region
                              (butlast segments)
                              segments))
           (base-name (if base-segments
                          (format nil "~{~a~^.~}" base-segments)
                          name))
           (type (or (pathname-type target-path) "bas"))
           (directory (pathname-directory target-path))
           (host (pathname-host target-path))
           (device (pathname-device target-path))
           (label-root (cl-change-case:pascal-case (pathname-base-name input-path))))
      (loop for region in '(:ntsc :pal :secam)
            for output-path = (make-pathname :host host
                                             :device device
                                             :directory directory
                                             :name (format nil "~a.~a" base-name (string-upcase (symbol-name region)))
                                             :type type)
            for label = (format nil "SetPlayfield~a"
                                label-root))
      do (let* ((*machine* 2600)
                (*region* conversion-region)
                (palette (png->palette rgb alpha))
                (rows (loop for y from 0 below height
                            collect (playfield-row->string palette width y)))
                (color-indices (loop for y from 0 below height
                                     collect (dominant-playfield-color palette width y)))
                (color-bytes (mapcar (lambda (idx)
                                       (playfield-color-byte idx region))
                                     color-indices)))
           (ensure-directories-exist output-path)
           (with-open-file (stream output-path
                                   :direction :output
                                   :if-exists :supersede
                                   :if-does-not-exist :create)
             (format stream "~a" label)
             (format stream "~%~10tplayfield:")
             (dolist (row rows)
               (format stream "~%~10t~a" row))
             (format stream "~%end")
             (format stream "~%~10tpfcolors:")
             (dolist (byte color-bytes)
               (format stream "~%~10t~a" (format-playfield-color byte)))
             (format stream "~%end")
             (format stream "~%~10treturn~%~%"))))
    output-bas))

(defun compile-chaos-character (output-bas png-path)
  (let* ((png-pathname (uiop:ensure-pathname png-path))
         (png (png-read:read-png-file png-pathname))
         (width (png-read:width png))
         (height (png-read:height png)))
    (unless (= width 64)
      (error "ChaosFight character sprites must be 64 pixels wide; got ~a" width))
    (unless (= height 256)
      (error "ChaosFight character sprites must be 256 pixels tall; got ~a" height))
    (let* ((palette (png->palette (png-read:image-data png)
                                  (png-read:transparency png)))
           (frames (make-array 0 :adjustable t :fill-pointer 0))
           (frame-cache (make-hash-table :test 'equal))
           (frame-map (make-array 16)))
      (dotimes (pose 16)
        (let ((row (make-array 8 :initial-element nil)))
          (dotimes (frame 8)
            (multiple-value-bind (frame-vector nonzero-p)
                (chaos-extract-frame palette frame pose)
              (when nonzero-p
                (setf (aref row frame)
                      (ensure-chaos-frame-index frame-vector frame-cache frames)))))
          (cond
            ((every #'null row)
             (if (plusp pose)
                 (setf row (copy-seq (aref frame-map (1- pose))))
                 (let ((blank-index (ensure-chaos-frame-index
                                     (make-array 16 :element-type '(unsigned-byte 8)
                                                    :initial-element 0)
                                     frame-cache frames)))
                   (dotimes (idx 8)
                     (setf (aref row idx) blank-index)))))
            (t
             (fill-chaos-row-indices row)))
          (setf (aref frame-map pose) (copy-seq row))))
      (let ((first-frame (aref frames 0)))
        (when (every #'zerop first-frame)
          (error "ChaosFight sprite ~a has blank action 0 frame 0"
                 (pathname-name (uiop:ensure-pathname png-path)))))
      (let* ((base-name (or (pathname-name (uiop:ensure-pathname png-path)) "Character"))
             (character-name (cl-change-case:pascal-case base-name))
             (output-path (uiop:ensure-pathname output-bas)))
        (ensure-directories-exist output-path)
        (with-open-file (stream output-path
                                :direction :output
                                :if-exists :supersede
                                :if-does-not-exist :create)
          (write-chaos-character-output stream character-name frames frame-map output-path png-path)))
      output-bas)))


