;;; Character Inspector — Single-Character Inspector
;;; Opens from All Resources context menu. Uses existing infrastructure
;;; for data loading (item-chooser, fountain) and drawing (misc-graphics).

(in-package :skyline-tool)

(defun bitset->indices (bytes)
  "Convert a list of BYTES to a list of set bit indices (0-63)."
  (loop for byte across (coerce bytes 'vector) for offset from 0 by 8
        append (loop for bit from 0 below 8
                     when (logbitp bit byte) collect (+ offset bit))))

(defun %set-bit (bytes index value)
  "Return a fresh copy of BYTES with bit INDEX set to VALUE (t/nil)."
  (let* ((byte-pos (floor index 8)) (bit-pos (mod index 8))
         (result (copy-list bytes)))
    (when (< byte-pos (length result))
      (setf (elt result byte-pos)
            (if value (logior (elt result byte-pos) (ash 1 bit-pos))
                (logand (elt result byte-pos) (lognot (ash 1 bit-pos))))))
    (coerce result 'list)))

(defun %test-atarivox (pitch speed bend phrase)
  (when *atarivox-port* (ignore-errors (close *atarivox-port*)) (setf *atarivox-port* nil))
  (handler-case
      (let ((stream (second (find-atarivox-serial-port))))
        (setf *atarivox-port* stream)
        (when pitch (write-byte 22 *atarivox-port*) (write-byte pitch *atarivox-port*))
        (when speed (write-byte 21 *atarivox-port*) (write-byte speed *atarivox-port*))
        (when bend (write-byte 23 *atarivox-port*) (write-byte bend *atarivox-port*))
        (speech-speak phrase :atarivox)
        (format *query-io* "~&AtariVox spoke: ~a~%" phrase) t)
    (error (e) (format *query-io* "~&AtariVox test failed: ~a~%" e) nil)))

(clim:define-presentation-type char-cmd () :inherit-from 'symbol :description "Character inspector command")

(clim:define-application-frame character-inspector-frame ()
  ((%npc :initarg :npc :accessor frame-npc)
   (%prototype :initarg :prototype :accessor frame-prototype)
   (%all-items :initarg :all-items :accessor frame-all-items)
   (%all-keys :initarg :all-keys :accessor frame-all-keys)
   (test-phrase :initform "Hello" :accessor frame-test-phrase))
  (:panes (left-pane :application :display-function 'display-left :height 700 :width 390 :scroll-bars :vertical)
          (right-pane :application :display-function 'display-right :height 700 :width 390 :scroll-bars :vertical)
          (interactor :interactor :height 80 :width 780))
  (:layouts (default (clim:vertically () (clim:horizontally () left-pane right-pane) interactor)))
  (:menu-bar char-inspector-menu-bar))

(defmethod initialize-instance :after ((frame character-inspector-frame) &key)
  (populate-char-print-menu frame))

(clim:define-command-table char-inspector-save-as-menu
  :menu (("Text..." :command com-char-save-text) ("JSON..." :command com-char-save) ("PDF..." :command com-char-save-pdf)))

(clim:define-command-table char-inspector-print-to-menu :menu ())

(clim:define-command-table char-inspector-file-menu
  :menu (("New..." :command com-char-new) ("Import from JSON..." :command com-char-import-json)
         ("Duplicate..." :command com-char-duplicate) (nil :divider :line)
         ("Save As" :menu char-inspector-save-as-menu) ("Print To" :menu char-inspector-print-to-menu)
         (nil :divider :line) ("Close" :command com-char-close)))

(clim:define-command-table char-inspector-edit-menu
  :menu (("Edit HP..." :command com-char-edit-hp) ("Edit Crowns..." :command com-char-edit-crowns)
         ("Edit Arrows..." :command com-char-edit-arrows) ("Edit Potions..." :command com-char-edit-potions)
         ("Edit Kind..." :command com-char-edit-kind)
         ("Edit Skin Color..." :command com-char-edit-skin) ("Edit Hair Color..." :command com-char-edit-hair)
         ("Edit Clothes Color..." :command com-char-edit-clothes)
         ("Edit Speech Color..." :command com-char-edit-speech-color)
         ("Edit Voice Pitch..." :command com-char-edit-pitch) ("Edit Voice Speed..." :command com-char-edit-speed)
         ("Edit Voice Bend..." :command com-char-edit-bend)
         ("Edit Weapon..." :command com-char-edit-weapon) ("Edit Shield..." :command com-char-edit-shield)
         ("Edit Armor..." :command com-char-edit-armor)))

(clim:define-command-table char-inspector-voice-menu
  :menu (("Test on AtariVox..." :command com-char-test-atarivox :keystroke (#\t :control))))

(clim:define-command-table char-inspector-help-menu
  :menu (("How to Edit Characters" :command com-help-for-window)
         ("Skyline-Tool Developers' Guide" :command com-open-dev-guide)
         ("Skyline-Tool Scripting Guide" :command com-open-scripting-guide)
         (nil :divider :line) ("About Skyline-Tool..." :command com-about-skyline-tool)))

(clim:define-command-table char-inspector-menu-bar
  :menu (("File" :menu char-inspector-file-menu) ("Edit" :menu char-inspector-edit-menu)
         ("Voice" :menu char-inspector-voice-menu) ("Help" :menu char-inspector-help-menu)))

(defmacro with-char-data ((npc proto all-items all-keys) &body body)
  `(let* ((,npc (frame-npc *application-frame*))
          (,proto (frame-prototype *application-frame*))
          (,all-items (or (frame-all-items *application-frame*) (load-item-list)))
          (,all-keys (or (frame-all-keys *application-frame*) (load-key-list))))
     ,@body))

(defun npc-val (npc key &optional default) (or (getf npc key) default))
(defun proto-val (proto key &optional default) (getf proto key default))

(defun %strip-prefix (name)
  (let* ((s (string name))
         (p (or (and (search "PaletteColor_" s :test #'char-equal) 13)
                (and (search "DecalKind" s :test #'char-equal) 9)
                (and (search "Equip" s :test #'char-equal) 5)
                (and (search "Shield" s :test #'char-equal) 6) 0)))
    (subseq s p)))

(defun display-left (frame pane)
  (clim:window-clear pane)
  (with-char-data (npc proto all-items all-keys)
    (unless npc (format pane "~&Character not found in NPCStats.ods.") (return-from display-left))
    (let ((name (npc-val npc :name (proto-val proto :|CharacterName| "?")))
          (class (npc-val npc :class (proto-val proto :|Class| "?")))
          (char-id (npc-val npc :character-id 0))
          (hp (npc-val npc :hp (proto-val proto :|CharacterHP| 0)))
          (max-hp (proto-val proto :|CharacterMaxHP| (npc-val npc :hp 0)))
          (ac (npc-val npc :ac (proto-val proto :|CharacterArmorClass| 0)))
          (crowns (npc-val npc :crowns (proto-val proto :|CharacterCrowns| 0)))
          (arrows (npc-val npc :arrows (proto-val proto :|CharacterArrows| 0)))
          (potions (npc-val npc :potions (proto-val proto :|CharacterPotions| 0)))
          (skin (%strip-prefix (npc-val npc :skin-color (proto-val proto :|CharacterSkinColor| "White"))))
          (hair (%strip-prefix (npc-val npc :hair-color (proto-val proto :|CharacterHairColor| "Brown"))))
          (clothes (%strip-prefix (npc-val npc :clothes-color (proto-val proto :|CharacterClothesColor| "Blue"))))
          (speech (npc-val npc :speech-color "Gray"))
          (pitch (npc-val npc :pitch (proto-val proto :|CharacterSpeechPitch| 96)))
          (speed (npc-val npc :speed (proto-val proto :|CharacterSpeechSpeed| 114)))
          (bend (npc-val npc :bend (proto-val proto :|CharacterSpeechBend| 5)))
          (equip (npc-val npc :equipment (proto-val proto :|CharacterEquipment| "EquipNone")))
          (shield (npc-val npc :shield (proto-val proto :|CharacterShield| "ShieldNoShield")))
          (kind-str (let ((dk (proto-val proto :|CharacterDecalKind| "DecalKindEnemy")))
                      (or (npc-val npc :kind) (and dk (subseq (string dk) 9))))))
      (clim:with-text-face (pane :bold) (clim:with-text-size (pane :large) (format pane "~a~%" name)))
      (format pane "Class: ~a  " class)
      (clim:with-output-as-presentation (pane :kind 'char-cmd :background-mode :transparent)
        (format pane "Kind: ~a" kind-str))
      (format pane "  ID: ~d~%~%" char-id)
      (format pane "~&HP: ~d / ~d     AC: ~d~%" hp (max hp max-hp) ac)
      (format pane "~&Crowns: ~d  Arrows: ~d  Potions: ~d~%~%" crowns arrows potions)
      (clim:with-text-face (pane :bold) (format pane "Appearance"))
      (format pane "~&  Skin: ") (print-wide-pixel 0 pane :unit 8)
      (clim:with-output-as-presentation (pane :skin 'char-cmd :background-mode :transparent)
        (format pane " ~a" skin))
      (format pane "~&  Hair: ") (print-wide-pixel 0 pane :unit 8)
      (clim:with-output-as-presentation (pane :hair 'char-cmd :background-mode :transparent)
        (format pane " ~a" hair))
      (format pane "~&  Clothes: ") (print-wide-pixel 0 pane :unit 8)
      (clim:with-output-as-presentation (pane :clothes 'char-cmd :background-mode :transparent)
        (format pane " ~a" clothes))
      (format pane "~2%")
      (clim:with-text-face (pane :bold) (format pane "Speech"))
      (format pane "~&  ")
      (print-clim-color 0 pane)
      (clim:with-output-as-presentation (pane :speech-color 'char-cmd :background-mode :transparent)
        (format pane " ~a" speech))
      (clim:with-output-as-presentation (pane :pitch 'char-cmd :background-mode :transparent)
        (format pane "  Pitch: ~d" pitch))
      (clim:with-output-as-presentation (pane :speed 'char-cmd :background-mode :transparent)
        (format pane "  Speed: ~d" speed))
      (clim:with-output-as-presentation (pane :bend 'char-cmd :background-mode :transparent)
        (format pane "  Bend: ~d" bend))
      (format pane "~&")
      (clim:with-output-as-presentation (pane :test-atarivox 'char-cmd :background-mode :transparent)
        (format pane "[Test on AtariVox]"))
      (format pane "~2%")
      (clim:with-text-face (pane :bold) (format pane "Inventory"))
      (format pane "~& Equipped ")
      (clim:with-output-as-presentation (pane :equip 'char-cmd :background-mode :transparent)
        (format pane "Item: ~a" (or (car (rassoc equip +equipment-names+ :test #'string-equal)) (%strip-prefix equip))))
      (format pane "~&  Equipped ")
      (clim:with-output-as-presentation (pane :shield 'char-cmd :background-mode :transparent)
        (format pane "Shield: ~a" (or (car (rassoc shield +shield-names+ :test #'string-equal)) (%strip-prefix shield))))
      (format pane "~&  Worn ")
      (clim:with-output-as-presentation (pane :armor 'char-cmd :background-mode :transparent)
        (format pane "Armor: ~a" (or (and all-items (loop for n in all-items when (search "armor" n :test #'char-equal) return n)) "None")))
      (format pane "~2%")
      (clim:with-text-face (pane :bold) (format pane "In Bag"))
      (let* ((inv-bytes (proto-val proto :|CharacterInventory| '(0 0 0 0 0 0 0 0)))
             (indices (bitset->indices (coerce inv-bytes 'list))))
        (if indices (dolist (idx indices)
                     (let ((n (if (< idx (length all-items)) (elt all-items idx) (format nil "#~d" idx))))
                       (clim:with-output-as-presentation (pane idx 'integer :background-mode :transparent) (format pane "~&  ~a" n))))
            (format pane "~&  (empty)")))
      (format pane "~2%")
      (clim:with-text-face (pane :bold) (format pane "Keys"))
      (let* ((key-bytes (proto-val proto :|CharacterKeys| '(0 0 0 0)))
             (indices (bitset->indices (coerce key-bytes 'list))))
        (if indices (dolist (idx indices)
                     (let ((n (if (< idx (length all-keys)) (elt all-keys idx) (format nil "Key #~d" idx))))
                       (clim:with-output-as-presentation (pane idx 'integer :background-mode :transparent) (format pane "~&  ~a" n))))
            (format pane "~&  (none)")))
      (format pane "~%")
      (when proto (format pane "~&~%(~a)" (proto-val proto :|Class| "?"))))))

(defun display-right (frame pane)
  (clim:window-clear pane)
  (with-char-data (npc proto all-items all-keys)
    (unless npc (return-from display-right))
    (clim:with-text-face (pane :bold) (format pane "Available~%"))
    (let* ((inv-bytes (proto-val proto :|CharacterInventory| '(0 0 0 0 0 0 0 0)))
           (owned (bitset->indices (coerce inv-bytes 'list))))
      (if all-items
          (let ((count 0))
            (loop for name across (coerce all-items 'vector) for idx from 0 unless (find idx owned)
                  do (when (< count 30) (incf count)
                      (clim:with-output-as-presentation (pane idx 'integer :background-mode :transparent) (format pane "~&  ~a" name))))
            (when (< count (length all-items)) (format pane "~&  ... and ~d more" (- (length all-items) count))))
          (format pane "~&  (no items loaded)")))
    (format pane "~2%")
    (clim:with-text-face (pane :bold) (format pane "Keys~%"))
    (let* ((key-bytes (proto-val proto :|CharacterKeys| '(0 0 0 0)))
           (owned (bitset->indices (coerce key-bytes 'list))))
      (if all-keys
          (loop for name across (coerce all-keys 'vector) for idx from 0 unless (find idx owned)
                do (clim:with-output-as-presentation (pane idx 'integer :background-mode :transparent) (format pane "~&  ~a" name)))
          (format pane "~&  (no keys loaded)")))
    (format pane "~%")))

(clim:define-command (com-char-equip-click :command-table clim-internals::global-command-table :menu nil :name t)
    ((slot 'char-cmd :gesture :select))
  (let* ((frame *application-frame*) (npc (frame-npc frame)) (proto (frame-prototype frame)))
    (unless npc (return-from com-char-equip-click))
    (ecase slot
      (:equip (let ((c (clim:accept `(clim:member-alist ,(loop for (l . v) in +equipment-names+ collect (list l v)) :value-type string) :prompt "Weapon")))
               (when c (setf (getf npc :equipment) c) (when proto (setf (getf proto :|CharacterEquipment|) c)))))
      (:shield (let ((c (clim:accept `(clim:member-alist ,(loop for (l . v) in +shield-names+ collect (list l v)) :value-type string) :prompt "Shield")))
                (when c (setf (getf npc :shield) c) (when proto (setf (getf proto :|CharacterShield|) c)))))
      (:armor (let ((names (or (frame-all-items frame) (load-item-list))))
                (let ((c (clim:accept `(clim:member-alist ,(loop for n in names collect (list n n)) :value-type string) :prompt "Armor")))
                  (when c (format *query-io* "~&Armor: ~a~%" c))))))
    (clim:redisplay-frame-panes frame)))

(clim:define-command (com-char-kind-click :command-table clim-internals::global-command-table :menu nil :name t)
    ((slot 'char-cmd :gesture :select))
  (let* ((frame *application-frame*) (proto (frame-prototype frame)))
    (unless (frame-npc frame) (return-from com-char-kind-click))
    (let ((c (clim:accept `(clim:member-alist ,(loop for (l . v) in +decal-kind-names+ collect (list l v)) :value-type string) :prompt "Kind")))
      (when c (when proto (setf (getf proto :|CharacterDecalKind|) c)) (clim:redisplay-frame-panes frame)))))

(clim:define-command (com-char-color-click :command-table clim-internals::global-command-table :menu nil :name t)
    ((which 'char-cmd :gesture :select))
  (let* ((frame *application-frame*) (npc (frame-npc frame)))
    (unless npc (return-from com-char-color-click))
    (let* ((cur (ecase which (:skin (%strip-prefix (getf npc :skin-color "White"))) (:hair (%strip-prefix (getf npc :hair-color "Brown"))) (:clothes (%strip-prefix (getf npc :clothes-color "Blue")))))
           (c (clim:accept `(clim:member-alist ,(loop for c in +palette-color-non-variable+ collect (list c c)) :value-type string)
                           :prompt (ecase which (:skin "Skin") (:hair "Hair") (:clothes "Clothes")) :default cur)))
      (when c (ecase which (:skin (setf (getf npc :skin-color) c)) (:hair (setf (getf npc :hair-color) c)) (:clothes (setf (getf npc :clothes-color) c)))
        (clim:redisplay-frame-panes frame)))))

(clim:define-command (com-char-speech-click :command-table clim-internals::global-command-table :menu nil :name t)
    ((slot 'char-cmd :gesture :select))
  (let* ((frame *application-frame*) (npc (frame-npc frame)) (proto (frame-prototype frame)))
    (unless npc (return-from com-char-speech-click))
    (flet ((col-name (s) (%col-name-string s)))
      (let* ((ntsc-names (mapcar #'col-name +atari-ntsc-color-names+))
             (pal-names (mapcar #'col-name +atari-pal-color-names+))
             (all-colors (remove-duplicates (append ntsc-names pal-names) :test #'string-equal))
             (c (clim:accept `(clim:member-alist ,(loop for c in all-colors collect (list c c)) :value-type string)
                             :prompt "COL" :default (getf npc :speech-color "Gray"))))
        (when c (setf (getf npc :speech-color) c) (when proto (setf (getf proto :|CharacterSpeechColor|) c)) (clim:redisplay-frame-panes frame))))))

(clim:define-command (com-char-voice-click :command-table clim-internals::global-command-table :menu nil :name t)
    ((which 'char-cmd :gesture :select))
  (let* ((frame *application-frame*) (npc (frame-npc frame)))
    (unless npc (return-from com-char-voice-click))
    (let* ((cur (ecase which (:pitch (getf npc :pitch 96)) (:speed (getf npc :speed 114)) (:bend (getf npc :bend 5))))
           (new (clim:accept 'integer :prompt (ecase which (:pitch "Pitch 0-255") (:speed "Speed 0-255") (:bend "Bend 0-255")) :default cur)))
      (setf (getf npc which) (max 0 (min 255 (or new cur)))) (clim:redisplay-frame-panes frame))))

(clim:define-command (com-char-test-click :command-table clim-internals::global-command-table :menu nil :name t)
    ((cmd 'char-cmd :gesture :select))
  (let* ((frame *application-frame*) (npc (frame-npc frame)))
    (unless npc (return-from com-char-test-click))
    (%test-atarivox (getf npc :pitch 96) (getf npc :speed 114) (getf npc :bend 5) (frame-test-phrase frame))))

(clim:define-command (com-char-inv-click :command-table clim-internals::global-command-table :menu nil :name t)
    ((idx 'integer :gesture :select))
  (let* ((frame *application-frame*) (proto (frame-prototype frame)) (items (or (frame-all-items frame) (load-item-list))))
    (unless proto (format *query-io* "~&No prototype — use File > Save Prototype first.~%") (return-from com-char-inv-click))
    (let* ((bytes (getf proto :|CharacterInventory| '(0 0 0 0 0 0 0 0)))
           (owned (bitset->indices (coerce bytes 'list))) (is-set (find idx owned))
           (new (%set-bit bytes idx (not is-set))) (name (if (< idx (length items)) (elt items idx) (format nil "#~d" idx))))
      (setf (getf proto :|CharacterInventory|) new)
      (format *query-io* "~&~a ~a~%" name (if is-set "removed from bag" "added to bag")) (clim:redisplay-frame-panes frame))))

(clim:define-command (com-char-edit-hp :menu t :name t) ()
  (let* ((frame *application-frame*) (npc (frame-npc frame))) (unless npc (return-from com-char-edit-hp))
    (let ((new (clim:accept 'integer :prompt "HP" :default (getf npc :hp 0)))) (setf (getf npc :hp) (max 0 new)) (clim:redisplay-frame-panes frame))))

(clim:define-command (com-char-edit-crowns :menu t :name t) ()
  (let* ((frame *application-frame*) (npc (frame-npc frame))) (unless npc (return-from com-char-edit-crowns))
    (let ((new (clim:accept 'integer :prompt "Crowns" :default (getf npc :crowns 0)))) (setf (getf npc :crowns) (abs new)) (clim:redisplay-frame-panes frame))))

(clim:define-command (com-char-edit-arrows :menu t :name t) ()
  (let* ((frame *application-frame*) (npc (frame-npc frame))) (unless npc (return-from com-char-edit-arrows))
    (let ((new (clim:accept 'integer :prompt "Arrows" :default (getf npc :arrows 0)))) (setf (getf npc :arrows) (abs new)) (clim:redisplay-frame-panes frame))))

(clim:define-command (com-char-edit-potions :menu t :name t) ()
  (let* ((frame *application-frame*) (npc (frame-npc frame))) (unless npc (return-from com-char-edit-potions))
    (let ((new (clim:accept 'integer :prompt "Potions" :default (getf npc :potions 0)))) (setf (getf npc :potions) (abs new)) (clim:redisplay-frame-panes frame))))

(clim:define-command (com-char-edit-kind :menu t :name t) ()
  (let* ((frame *application-frame*) (proto (frame-prototype frame))) (unless proto (format *query-io* "~&No prototype.~%") (return-from com-char-edit-kind))
    (let ((c (clim:accept `(clim:member-alist ,(loop for (l . v) in +decal-kind-names+ collect (list l v)) :value-type string) :prompt "Kind")))
      (when c (setf (getf proto :|CharacterDecalKind|) c) (clim:redisplay-frame-panes frame)))))

(clim:define-command (com-char-edit-skin :menu t :name t) ()
  (let* ((frame *application-frame*) (npc (frame-npc frame))) (unless npc (return-from com-char-edit-skin))
    (let ((c (clim:accept `(clim:member-alist ,(loop for c in +palette-color-non-variable+ collect (list c c)) :value-type string)
                          :prompt "Skin" :default (%strip-prefix (getf npc :skin-color "White")))))
      (when c (setf (getf npc :skin-color) c) (clim:redisplay-frame-panes frame)))))

(clim:define-command (com-char-edit-hair :menu t :name t) ()
  (let* ((frame *application-frame*) (npc (frame-npc frame))) (unless npc (return-from com-char-edit-hair))
    (let ((c (clim:accept `(clim:member-alist ,(loop for c in +palette-color-non-variable+ collect (list c c)) :value-type string)
                          :prompt "Hair" :default (%strip-prefix (getf npc :hair-color "Brown")))))
      (when c (setf (getf npc :hair-color) c) (clim:redisplay-frame-panes frame)))))

(clim:define-command (com-char-edit-clothes :menu t :name t) ()
  (let* ((frame *application-frame*) (npc (frame-npc frame))) (unless npc (return-from com-char-edit-clothes))
    (let ((c (clim:accept `(clim:member-alist ,(loop for c in +palette-color-non-variable+ collect (list c c)) :value-type string)
                          :prompt "Clothes" :default (%strip-prefix (getf npc :clothes-color "Blue")))))
      (when c (setf (getf npc :clothes-color) c) (clim:redisplay-frame-panes frame)))))

(clim:define-command (com-char-edit-speech-color :menu t :name t) ()
  (let* ((frame *application-frame*) (npc (frame-npc frame))) (unless npc (return-from com-char-edit-speech-color))
    (flet ((col-name (s) (%col-name-string s)))
      (let* ((ntsc (mapcar #'col-name +atari-ntsc-color-names+)) (pal (mapcar #'col-name +atari-pal-color-names+))
             (all (remove-duplicates (append ntsc pal) :test #'string-equal))
             (c (clim:accept `(clim:member-alist ,(loop for c in all collect (list c c)) :value-type string) :prompt "COL" :default (getf npc :speech-color "Gray"))))
        (when c (setf (getf npc :speech-color) c) (when (frame-prototype frame) (setf (getf (frame-prototype frame) :|CharacterSpeechColor|) c)) (clim:redisplay-frame-panes frame))))))

(clim:define-command (com-char-edit-pitch :menu t :name t) ()
  (let* ((frame *application-frame*) (npc (frame-npc frame))) (unless npc (return-from com-char-edit-pitch))
    (let ((n (clim:accept 'integer :prompt "Pitch 0-255" :default (getf npc :pitch 96)))) (setf (getf npc :pitch) (max 0 (min 255 n))) (clim:redisplay-frame-panes frame))))

(clim:define-command (com-char-edit-speed :menu t :name t) ()
  (let* ((frame *application-frame*) (npc (frame-npc frame))) (unless npc (return-from com-char-edit-speed))
    (let ((n (clim:accept 'integer :prompt "Speed 0-255" :default (getf npc :speed 114)))) (setf (getf npc :speed) (max 0 (min 255 n))) (clim:redisplay-frame-panes frame))))

(clim:define-command (com-char-edit-bend :menu t :name t) ()
  (let* ((frame *application-frame*) (npc (frame-npc frame))) (unless npc (return-from com-char-edit-bend))
    (let ((n (clim:accept 'integer :prompt "Bend 0-255" :default (getf npc :bend 5)))) (setf (getf npc :bend) (max 0 (min 255 n))) (clim:redisplay-frame-panes frame))))

(clim:define-command (com-char-edit-weapon :menu t :name t) ()
  (let* ((frame *application-frame*) (npc (frame-npc frame)) (proto (frame-prototype frame))) (unless npc (return-from com-char-edit-weapon))
    (let ((c (clim:accept `(clim:member-alist ,(loop for (l . v) in +equipment-names+ collect (list l v)) :value-type string) :prompt "Weapon")))
      (when c (setf (getf npc :equipment) c) (when proto (setf (getf proto :|CharacterEquipment|) c)) (clim:redisplay-frame-panes frame)))))

(clim:define-command (com-char-edit-shield :menu t :name t) ()
  (let* ((frame *application-frame*) (npc (frame-npc frame)) (proto (frame-prototype frame))) (unless npc (return-from com-char-edit-shield))
    (let ((c (clim:accept `(clim:member-alist ,(loop for (l . v) in +shield-names+ collect (list l v)) :value-type string) :prompt "Shield")))
      (when c (setf (getf npc :shield) c) (when proto (setf (getf proto :|CharacterShield|) c)) (clim:redisplay-frame-panes frame)))))

(clim:define-command (com-char-edit-armor :menu t :name t) ()
  (let* ((frame *application-frame*) (names (or (frame-all-items frame) (load-item-list))))
    (let ((c (clim:accept `(clim:member-alist ,(loop for n in names collect (list n n)) :value-type string) :prompt "Armor")))
      (when c (format *query-io* "~&Armor: ~a~%" c)))))

(clim:define-command (com-char-test-atarivox :menu t :name t) ()
  (let* ((frame *application-frame*) (npc (frame-npc frame))) (unless npc (format *query-io* "~&No character.~%") (return-from com-char-test-atarivox))
    (let ((pitch (getf npc :pitch 96)) (speed (getf npc :speed 114)) (bend (getf npc :bend 5))
          (phrase (clim:accept 'string :prompt "Test phrase" :default (frame-test-phrase frame))))
      (setf (frame-test-phrase frame) phrase) (%test-atarivox pitch speed bend phrase))))

(clim:define-command (com-char-save :menu t :name t) ()
  (let* ((frame *application-frame*) (npc (frame-npc frame)) (proto (frame-prototype frame)))
    (unless proto
      (setf proto (list :|Class| "NPC" :|CharacterName| (getf npc :name "Unknown")
                        :|CharacterCharacterID| (getf npc :character-id 0)
                        :|CharacterHP| (getf npc :hp 10) :|CharacterMaxHP| (getf npc :hp 10)
                        :|CharacterArmorClass| (getf npc :ac 0) :|CharacterCrowns| (getf npc :crowns 0)
                        :|CharacterArrows| (getf npc :arrows 0) :|CharacterPotions| (getf npc :potions 0)
                        :|CharacterInventory| '(0 0 0 0 0 0 0 0) :|CharacterKeys| '(0 0 0 0)
                        :|CharacterEquipment| "EquipNone" :|CharacterShield| "ShieldNoShield"
                        :|CharacterDecalKind| "DecalKindEnemy" :|CharacterAction| "ActionIdle"
                         :|ActorFacing| "ActorFacingDown" :|ActorCourse| 0 :|EntityDecal| 255))
      (setf (frame-prototype frame) proto))
    (let* ((name (or (getf proto :|CharacterName|) (and npc (getf npc :name)) "Unknown"))
           (file (merge-pathnames (make-pathname :name name :type "json") (merge-pathnames "Source/Objects/" (uiop:getcwd)))))
      (ensure-directories-exist file)
      (with-open-file (s file :direction :output :if-exists :supersede :external-format :utf-8)
        (let ((json:*json-identifier-name-to-lisp* nil))
          (json:encode-json-alist
           (loop for (k v) on proto by #'cddr when (and k v) collect (cons (string k) (if (listp v) (copy-list v) v))) s)))
      (format *query-io* "~&Saved ~a~%" file))))

(clim:define-command (com-char-new :menu t :name t) ()
  (let* ((frame *application-frame*) (name (clim:accept 'string :prompt "Character name")))
    (setf (frame-npc frame) (list :name name :character-id 0 :hp 10 :ac 0) (frame-prototype frame) nil)
    (setf (frame-pretty-name frame) (format nil "Character Inspector — ~a" name)) (clim:redisplay-frame-panes frame)))

(clim:define-command (com-char-import-json :menu t :name t) ()
  (let* ((frame *application-frame*) (path (clim:accept 'pathname :prompt "JSON" :default #p"Source/Objects/*.json")))
    (when (and path (probe-file path))
      (let* ((data (load-prototype-file path)) (plist (loop for (key . val) in data append (list key val)))
             (name (or (getf plist :|CharacterName|) (pathname-name path))))
        (setf (frame-npc frame) (list :name name :character-id (or (getf plist :|CharacterCharacterID|) 0)))
        (setf (frame-prototype frame) plist)
        (setf (frame-pretty-name frame) (format nil "Character Inspector — ~a" name))
        (clim:redisplay-frame-panes frame)))))

(clim:define-command (com-char-duplicate :menu t :name t) ()
  (let* ((frame *application-frame*) (npc (frame-npc frame)) (proto (frame-prototype frame))
         (new-name (format nil "~a Copy" (or (and npc (getf npc :name)) (and proto (getf proto :|CharacterName|)) "Unknown"))))
    (setf (frame-npc frame) (list :name new-name :character-id 0 :hp (and npc (getf npc :hp 10)) :ac (and npc (getf npc :ac 0))))
    (when proto (let ((new (copy-list proto))) (setf (getf new :|CharacterName|) new-name (getf new :|CharacterCharacterID|) 0) (setf (frame-prototype frame) new)))
    (setf (frame-pretty-name frame) (format nil "Character Inspector — ~a" new-name)) (clim:redisplay-frame-panes frame)))

(clim:define-command (com-char-save-text :menu t :name t) ()
  (let* ((frame *application-frame*) (npc (frame-npc frame)) (proto (frame-prototype frame))
         (name (or (and npc (getf npc :name)) (and proto (getf proto :|CharacterName|)) "Character"))
         (path (prompt-save-pathname (format nil "~a.txt" name) :type "txt")))
    (when path
      (with-open-file (s path :direction :output :if-exists :supersede :external-format :utf-8)
        (when npc (format s "Name: ~a~%" (getf npc :name)) (format s "Class: ~a~%" (getf npc :class))
          (format s "ID: ~d~%" (getf npc :character-id)) (format s "HP: ~d/~d  AC: ~d~%" (getf npc :hp 0) (getf npc :hp 0) (getf npc :ac 0))
          (format s "Crowns: ~d  Arrows: ~d  Potions: ~d~%" (getf npc :crowns 0) (getf npc :arrows 0) (getf npc :potions 0))
          (format s "Pitch: ~d  Speed: ~d  Bend: ~d~%" (getf npc :pitch 96) (getf npc :speed 114) (getf npc :bend 5)))
        (when proto (format s "~%Prototype:~%") (loop for (k v) on proto by #'cddr do (format s "  ~a = ~a~%" k v))))
      (format *query-io* "~&Saved ~a~%" path))))

(clim:define-command (com-char-save-pdf :menu t :name t) ()
  (let* ((frame *application-frame*) (npc (frame-npc frame)) (name (or (and npc (getf npc :name)) "Character"))
         (path (prompt-save-pathname (format nil "~a.pdf" name) :type "pdf")))
    (when path
      (let ((ps-path (make-pathname :type "ps" :defaults path)))
        (with-open-file (ps ps-path :direction :output :if-exists :supersede)
          (format ps "%!PS-Adobe-3.0~%") (write-ps-docinfo ps (format nil "Character: ~a" name) "Skyline-Tool" (format nil "~a on ~a" (user-real-name) (machine-instance)))
          (format ps "<< /PageSize [612 792] >> setpagedevice~%") (write-ps-font-encodings ps) (format ps "%%Page: 1 1~%")
          (write-ps-header-bar ps name) (let ((y 700))
            (when npc (format ps "50 ~d moveto (Class: ~a) show~%" y (or (getf npc :class) "?")) (decf y 14)
              (format ps "50 ~d moveto (HP: ~d/~d) show~%" y (getf npc :hp 0) (getf npc :hp 0)) (decf y 14)
              (format ps "50 ~d moveto (Crowns: ~d) show~%" y (getf npc :crowns 0)) (decf y 14)
              (format ps "50 ~d moveto (Pitch: ~d  Speed: ~d  Bend: ~d) show~%" y (getf npc :pitch 96) (getf npc :speed 114) (getf npc :bend 5))))
          (write-ps-page-footer ps 1 1 name (multiple-value-bind (s m h d mo y) (get-decoded-time) (declare (ignore s m h d)) (format nil "~d-~2,'0d" mo y)) (user-real-name))
          (format ps "showpage~%"))
        (uiop:run-program (list "ps2pdf" (namestring ps-path) (namestring path)) :output nil :ignore-error-status t)
        (ignore-errors (delete-file ps-path)) (format *query-io* "~&Saved ~a~%" path)))))

(clim:define-command (com-char-close :menu t :name t) ()
  (let ((frame *application-frame*)) (when (typep frame 'character-inspector-frame) (clim:frame-exit frame))))

(defun populate-char-print-menu (&optional frame)
  (let ((ct 'char-inspector-print-to-menu))
    (ignore-errors (clim:remove-menu-item-from-command-table ct "No printers found")
     (clim:remove-menu-item-from-command-table ct "Default Printer (lpr)"))
    (let ((printers (ignore-errors (discover-printers-with-names))))
      (if printers (dolist (pair printers)
                    (let ((queue (car pair)) (display (cdr pair)))
                      (clim:add-menu-item-to-command-table ct display :command `(com-char-print-to ,queue ,display) :after :end)))
          (clim:add-menu-item-to-command-table ct "Default Printer (lpr)" :function (lambda (g n) (declare (ignore g n)) (%char-print-to-printer nil)) :after :end :value t))))
  (unless (fboundp 'com-char-print-to)
    (clim:define-command (com-char-print-to :command-table clim-internals::global-command-table :menu nil :name t)
        ((queue-name 'string) (display-name 'string))
      (declare (ignore display-name)) (%char-print-to-printer queue-name))))

(defun %char-print-to-printer (queue-name)
  (let* ((frame *application-frame*) (npc (frame-npc frame)) (name (or (and npc (getf npc :name)) "Character")))
    (com-char-save-pdf)
    (let ((pdf (format nil "/tmp/char-~a.pdf" name)))
      (when (probe-file pdf)
        (uiop:run-program (if queue-name (list "lp" "-d" queue-name pdf) (list "lp" pdf)) :output nil :ignore-error-status t)
        (format *query-io* "~&Printed ~a~%" name)))))

(defun open-character-inspector (character-name)
  "Open the Character Inspector for a CHARACTER-NAME string (matching NPCStats.ods)."
  (let* ((npc (%find-char-in-ods character-name))
         (char-id (and npc (getf npc :character-id)))
         (proto (and char-id (%find-prototype-for-char-id char-id)))
         (all-items (load-item-list)) (all-keys (load-key-list))
         (frame (clim:make-application-frame 'character-inspector-frame
                 :pretty-name (format nil "Character Inspector — ~a" character-name)
                 :npc npc :prototype proto :all-items all-items :all-keys all-keys
                 :width 800 :height 800)))
    (clim:run-frame-top-level frame)))

(defun run-character-inspector (&optional character-name)
  (let ((name (or character-name (clim:accept 'string :prompt "Character name"))))
    (open-character-inspector name)))
