(in-package :skyline-tool)
(defun print-ansi-cell-pattern (palette-pixels x y w h stream)
  "Print a single ANSI cell using 5-sample weighted algorithm."
  (let* ((all-colors (region-pixel-colors palette-pixels x y w h))
         (unique-colors (remove-duplicates all-colors :test #'equal))
         (ansi-p (and (not (typep stream 'string-stream))
                      (tty-xterm-p))))
    (when (<= (length unique-colors) 1)
      (let ((color (or (first unique-colors) (list 0 0 0))))
        (print-wide-pixel color stream)
        (return-from print-ansi-cell-pattern)))
    (multiple-value-bind (center-rgb tl-rgb tr-rgb bl-rgb br-rgb)
         (cell-5-weighted-samples palette-pixels x y w h)
      (let* ((median (median-lightness all-colors))
             (light-avg (average-rgb-via-xyz (remove-if (lambda (c) (> (rgb-hsl-lightness c) median))
                                                   all-colors)))
             (dark-avg (average-rgb-via-xyz (remove-if (lambda (c) (<= (rgb-hsl-lightness c) median))
                                                   all-colors)))
             (pattern (list (classify-sample-lightness center-rgb median)
                            (classify-sample-lightness tl-rgb median)
                            (classify-sample-lightness tr-rgb median)
                            (classify-sample-lightness bl-rgb median)
                            (classify-sample-lightness br-rgb median))))
        (multiple-value-bind (char fg bg)
             (pattern->char-fg-bg pattern center-rgb tl-rgb tr-rgb bl-rgb br-rgb
                                  light-avg dark-avg median)
          (princ (ansi-color-pixel (first fg) (second fg) (third fg)))
          (princ char)
          (princ (ansi-color-pixel (first bg) (second bg) (third bg)))
          (terpri))))))EOF
tail -n +148 thumbnails.lisp >> thumbnails-new.lisp && mv thumbnails-new.lisp thumbnails.lisp
